object Versions {
    const val splashScreen = "1.0.1"
    const val core_ktx = "1.12.0"
    const val fragment_ktx = "1.6.1"
    const val appcompat = "1.6.1"
    const val material = "1.9.0"
    const val constraintlayout = "2.1.4"
    const val junit = "4.13.2"
    const val ext_junit = "1.1.5"
    const val espresso = "3.5.1"
    const val lifeCycle = "2.6.2"
    const val ktor = "2.3.5"
    const val kotlinxSerialization = "1.6.0"
    const val koin = "3.5.0"
    const val timber = "5.0.1"
    const val coil = "2.4.0"
    const val cardView = "1.0.0"
    const val kotlinCoroutine = "1.7.3"
    const val media3 = "1.2.0"
    const val gson = "2.10"
    const val paging = "3.2.1"
    const val palette = "1.0.0"
}